export const INTERNSHIP_OCCUPATIONS_REQUEST = 'INTERNSHIP_OCCUPATIONS_REQUEST'
export const INTERNSHIP_OCCUPATIONS_GET_ALL = 'INTERNSHIP_OCCUPATIONS_GET_ALL'
export const INTERNSHIP_OCCUPATIONS_GET_ALL_SUCCESS =
  'INTERNSHIP_OCCUPATIONS_GET_ALL_SUCCESS'
export const INTERNSHIP_OCCUPATIONS_GET_ALL_ERROR =
  'INTERNSHIP_OCCUPATIONS_GET_ALL_ERROR'

export const INTERNSHIP_OCCUPATIONS_GET = 'INTERNSHIP_OCCUPATIONS_GET'
export const INTERNSHIP_OCCUPATIONS_GET_SUCCESS = 'INTERNSHIP_OCCUPATIONS_GET_SUCCESS'
export const INTERNSHIP_OCCUPATIONS_GET_ERROR = 'INTERNSHIP_OCCUPATIONS_GET_ERROR'

export const INTERNSHIP_OCCUPATIONS_CREATE = 'INTERNSHIP_OCCUPATIONS_CREATE'
export const INTERNSHIP_OCCUPATIONS_CREATE_SUCCESS =
  'INTERNSHIP_OCCUPATIONS_CREATE_SUCCESS'
export const INTERNSHIP_OCCUPATIONS_CREATE_ERROR =
  'INTERNSHIP_OCCUPATIONS_CREATE_ERROR'
export const INTERNSHIP_OCCUPATIONS_UPDATE = 'INTERNSHIP_OCCUPATIONS_UPDATE'
export const INTERNSHIP_OCCUPATIONS_UPDATE_SUCCESS =
  'INTERNSHIP_OCCUPATIONS_UPDATE_SUCCESS'
export const INTERNSHIP_OCCUPATIONS_UPDATE_ERROR =
  'INTERNSHIP_OCCUPATIONS_UPDATE_ERROR'
export const INTERNSHIP_OCCUPATIONS_DELETE = 'INTERNSHIP_OCCUPATIONS_DELETE'
export const INTERNSHIP_OCCUPATIONS_DELETE_SUCCESS =
  'INTERNSHIP_OCCUPATIONS_DELETE_SUCCESS'
export const GET_INTERNSHIP_OCCUPATIONS_CATEGORY_DATA =
  'GET_INTERNSHIP_OCCUPATIONS_CATEGORY_DATA'
export const INTERNSHIP_OCCUPATIONS_DATA =
  'INTERNSHIP_OCCUPATIONS_FEATURES_DATA'
export const INTERNSHIP_OCCUPATIONS_EDIT = 'INTERNSHIP_OCCUPATIONS_EDIT'
