export const PLANS_REQUEST = 'PLANS_REQUEST'
export const PLANS_GET_ALL = 'PLANS_GET_ALL'
export const PLANS_GET_ALL_SUCCESS = 'PLANS_GET_ALL_SUCCESS'

export const PLANS_GET = 'PLANS_GET'
export const PLANS_GET_SUCCESS = 'PLANS_GET_SUCCESS'

export const PLANS_UPDATE = 'PLANS_UPDATE'
export const PLANS_UPDATE_SUCCESS = 'PLANS_UPDATE_SUCCESS'
