export const POSTAL_CODE_REQUEST = 'POSTAL_CODE_REQUEST'
export const POSTAL_CODE_GET_ALL = 'POSTAL_CODE_GET_ALL'
export const POSTAL_CODE_GET_ALL_SUCCESS = 'POSTAL_CODE_GET_ALL_SUCCESS'
export const POSTAL_CODE_GET_ALL_ERROR = 'POSTAL_CODE_GET_ALL_ERROR'
